### PR TITLE
Mfx ipm and valve

### PR DESCRIPTION
**Pull request by jsheppard95**
Added MFX:DG1:IPM
Corrected name mfx_dg2_valve (MFX:DIA:VGC:02) to mfx_dia_valve_02
Changed name of MFX:DIA:VGC:01 from mfx_dia_valve to mfx_dia_valve_01 (to differentiate)

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Nice, you try and load the actual Ophyd object and check it out? https://pcdshub.github.io/happi/client_api.html#happi.Client.load_device

**Comment by jsheppard95** [comment]
@teddyrendahl No I didn't but I'll try that now!

**Comment by jsheppard95** [comment]
Instantiating Ophyd objects using `client.load_device`
`In [1]: import happi`

`In [2]: client = happi.Client(path='/reg/neh/home/sheppard/PCDSGitHub/device_config/db.json')`

`In [3]: mfx_dg1_ipm = client.load_device(name='mfx_dg1_ipm')`

`In [4]: mfx_dg1_ipm.component_names`
`Out[4]: ('state', 'readback', 'diode')`

`In [5]: mfx_dg1_ipm.state.get()`
`Out[5]: 3`

`In [8]: mfx_dia_valve_01 = client.load_device(name='mfx_dia_valve_01')`

`In [9]: mfx_dia_valve_01.component_names`
`Out[9]: ('state', 'open_limit', 'closed_limit', 'command', 'interlock')`

`In [10]: mfx_dia_valve_01.state.get()`
`Out[10]: 'OUT'`

`In [12]: mfx_dia_valve_02 = client.load_device(name='mfx_dia_valve_02')`

`In [13]: mfx_dia_valve_02.component_names`
`Out[13]: ('state', 'open_limit', 'closed_limit', 'command', 'interlock')`

`In [17]: mfx_dia_valve_02.open_limit.get()`
`Out[17]: 1`

**Comment by teddyrendahl** [comment]
Looks good to me! In general `.wait_for_connection` is good to call. This forces connections to all the EPICS PVs on the `ophyd.Device`. I trust this is correct. One more thing.

Can you add the MFX DG2 IPM as well? I think it is missing.

**Comment by jsheppard95** [comment]
`In [1]: import happi`

`In [2]: client = happi.Client(path='/reg/neh/home/sheppard/PCDSGitHub/device_config/db.json')`

`In [3]: mfx_dg2_ipm = client.load_device(name='mfx_dg2_ipm')`

`In [4]: mfx_dg2_ipm.wait_for_connection()`

`In [5]: mfx_dg2_ipm.component_names`
`Out[5]: ('state', 'readback', 'diode')`

`In [6]: mfx_dg2_ipm.readback.get()`
`Out[6]: 6.0009765625`

**Pull request merged**
