### PR TITLE
Deploy Branch Status (October / November 2022)

### PR DESCRIPTION
**Pull request by klauer**
*** Not to be merged during October ***

This PR can be used to easily see when cron-based pushes to GitHub happen, and allow us an opportunity to review changes prior to merging into master.

(We still have not addressed #33 and we should before the end of this month)

### CODE REVIEW

**Comment by klauer** [comment]
Per Zach: https://pswww.slac.stanford.edu/pcds/git/PCDS/PSCron_Jobs/src/branch/main/pennebak

**Comment by klauer** [comment]
Here we are in December but we still rely on Tyler's cron job. Maybe 2023?

**Comment by tangkong** [comment]
Comparing to my device_config, the major changes seem to be
* leviton device changes
* Lightpath device modifications

lots of devices got moved around so the diff is also unintelligible locally.  :(

**Review by tangkong — APPROVED** [review]

**Comment by ZLLentz** [comment]
> lots of devices got moved around so the diff is also unintelligible locally
That's unfortunate. I'll take a peek locally as well but I suspect everything is fine and this is just to see if there's anyone we need to talk to.

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
I'm going to do the merge now in advance of the next push and bring "figure out how to securely set up fine-grained PATs to set up this sync using one of our users" up higher in my to-do list

**Pull request merged**
